### ISSUE TITLE
Xcode warning due to outdated dependency

### ISSUE THREAD

**Issue by simonmcl** [torusresearch/torus-utils-swift#5]
There is a warning in xcode when including this package thats coming from a dependency way down the chain. The problem is that you are using a fork of web3swift: https://github.com/rathishubham7/web3swift . This is using an outdated version of `starscream` and the fork itself is ~100 commits behind the official library.

I'm trying to keep my xcode clean and also very concerned about how outdated the dependencies are across these libraries. Can you please spend some time updating these? i've had to deal with a large number of issues and workarounds so far to get this imported, but I can't do anything about this one.

![Screenshot 2021-07-08 at 12 48 14](https://user-images.githubusercontent.com/8058386/124916651-cd061000-dfea-11eb-9e7c-1dc457c2c8fe.png)

**Comment by rathishubham7** [comment]
Which version of Xcode are you using? 

(Starscream/web3swift has not released the latest version. 12.5 still fetches the older version of startscream)

**Comment by simonmcl** [comment]
@rathishubham7 i'm using Xcode 12.5. The versions have been released, see below

Starscream merged a PR to handle this in July: https://github.com/daltoniam/Starscream/pull/807
Starscream cut a tag `4.0.0` in august: https://github.com/daltoniam/Starscream/tags
Official Web3Swift has been updated to this version: https://github.com/skywinder/web3swift/blob/develop/Package.swift

The problem is the version of web3Swift that this repo uses is very far behind

**Comment by rathishubham7** [comment]
There's a manifest parsing bug in the released version of web3swift. I can not pin the package to a branch because of the following (from swift documentation):

    /// Note that packages that use branch-based dependency requirements
    /// can't be depended upon by packages that use version-based dependency
    /// requirements; you should remove branch-based dependency requirements
    /// before publishing a version of your package.

Another solution is to update the fork.

**Comment by rathishubham7** [comment]
This has been fixed in the latest commit.
