### ISSUE TITLE
secp256k1: Use lib functions instead of custom implementations?

### ISSUE THREAD

**Issue by matthiasgeihs** [torusresearch/torus-utils-swift#63]
In [SECP256k1.swift](https://github.com/torusresearch/torus-utils-swift/blob/master/Sources/TorusUtils/Convenience/SECP256k1.swift) we have implementations of ecdh and signing with pubkey recovery. On the other hand, the secp256k1 library that we use seems to have these functions baked in (see [README](https://github.com/GigaBitcoin/secp256k1.swift#elliptic-curve-diffie-hellman)).

### Suggestion
Replace custom implementations of ecdh and signing with pubkey recovery in `torus-utils-swift` with function calls to the corresponding methods of the `secp256k1.swift` library.

**Comment by metalurgical** [comment]
Just to add more context to this issue. There is actually a discrepancy here between SPM and cocoapods. The secp256k1 for gigabitcoin is not available on cocoapods, the boilertalk secp256k1 is used instead.

**Comment by matthiasgeihs** [comment]
The original issue I pointed out here is resolved in #66.

@metalurgical Anything else that is left open in your opinion? If so, please reopen or create a different issue.
